-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ADC_personal\Subsystem.vhd
-- Created: 2026-04-16 17:40:39
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 4e-09
-- Target subsystem base rate: 4e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        4e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Digital                       ce_out        4e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: ADC_personal/Subsystem
-- Hierarchy Level: 0
-- Model version: 1.17
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        ce_out                            :   OUT   std_logic;
        Digital                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Component Declarations
  COMPONENT nfp_convert_double_to_fixed_16_En14
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in                          :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_convert_double_to_fixed_16_En14
    USE ENTITY work.nfp_convert_double_to_fixed_16_En14(rtl);

  -- Signals
  SIGNAL Data_Type_Conversion_out1        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Analog                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Digital_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_ADC_personal_Subsystem_nfp_convert_double_to_fixed_16_En14 : nfp_convert_double_to_fixed_16_En14
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in => In1,  -- double
              nfp_out => Data_Type_Conversion_out1  -- sfix16_En14
              );

  Analog <= signed(Data_Type_Conversion_out1);

  
  Digital_tmp <= to_signed(16#2000#, 16) WHEN Analog > to_signed(16#2000#, 16) ELSE
      to_signed(-16#2000#, 16) WHEN Analog < to_signed(-16#2000#, 16) ELSE
      Analog;

  Digital <= std_logic_vector(Digital_tmp);

  ce_out <= clk_enable;

END rtl;

